ALTER TYPE "Achievement" ADD VALUE IF NOT EXISTS 'GAMES_TOTAL_25';
ALTER TYPE "Achievement" ADD VALUE IF NOT EXISTS 'GAMES_TOTAL_50';
ALTER TYPE "Achievement" ADD VALUE IF NOT EXISTS 'GAMES_TOTAL_100';
ALTER TYPE "Achievement" ADD VALUE IF NOT EXISTS 'GAMES_TOTAL_200';
ALTER TYPE "Achievement" ADD VALUE IF NOT EXISTS 'GAMES_TOTAL_500';
ALTER TYPE "Achievement" ADD VALUE IF NOT EXISTS 'GAMES_TOTAL_1000';
