// ===================== GAE METAS =====================
const GAME_METAS = [
    {
        name: "Addition & Subtraction",
        code: "ADD_SUB",
        levels: ["L1", "L2", "L3", "L4"],
    },
    {
        name: "Multiplication",
        code: "MUL",
        levels: ["L1", "L2", "L3", "L4"],
    },
    {
        name: "Division",
        code: "DIV",
        levels: ["L1", "L2", "L3", "L4"],
    },
];

// ===================== GAME LEVEL DESCRIPTIONS =====================
const GAME_LEVELS = {
    ADD_SUB: {
        L1: {
            title: 'Beginner',
            importance: 'Builds basic mental addition and subtraction skills.',
            concepts:
                'Single digit calculations, short sequences, simple carry/borrow, increasing number of operands.',
        },
        L2: {
            title: 'Intermediate',
            importance:
                'Strengthens mental agility and accuracy with larger numbers.',
            concepts:
                'Two digit addition/subtraction, introduction to three digit numbers, longer sequences, maintaining focus under time pressure.',
        },
        L3: {
            title: 'Advanced',
            importance:
                'Prepares learners for complex calculations in speed challenges.',
            concepts:
                'Multiple two and three digit numbers, multi-step addition/subtraction, faster calculation under shorter delays.',
        },
        L4: {
            title: 'Pro',
            importance:
                'Develops high-speed mental computation and advanced problem-solving.',
            concepts:
                'Three to six digit operations, multi-step sequences, handling carry/borrow over multiple digits, precision under tight timing.',
        },
    },
    MUL: {
        L1: {
            title: 'Beginner',
            importance: 'Establishes fundamental multiplication skills.',
            concepts:
                'Single and two digit multiplication, small number sequences, visualizing multiplication patterns.',
        },
        L2: {
            title: 'Intermediate',
            importance:
                'Builds speed and confidence with multi-digit multiplication.',
            concepts:
                'Two to three digit multipliers, sequences of two to five numbers, mental multiplication strategies, improving calculation speed.',
        },
        L3: {
            title: 'Advanced',
            importance: 'Enhances mental stamina and advanced multiplication skills.',
            concepts:
                'Multi-digit multiplication, sequences of four to six numbers, combination of speed and accuracy, handling complex multiplications in mind.',
        },
        L4: {
            title: 'Pro',
            importance: 'Prepares learners for highly challenging mental math.',
            concepts:
                'Higher digit multipliers (up to 4 digits), small but precise sequences, rapid computation under strict time constraints, reinforcing mastery of multiplication patterns.',
        },
    },
    DIV: {
        L1: {
            title: 'Beginner',
            importance:
                'Introduces basic division and builds confidence in handling numbers mentally.',
            concepts:
                'Single digit dividends and divisors, understanding division as equal grouping, simple quotients, basic remainders.',
        },
        L2: {
            title: 'Intermediate',
            importance:
                'Strengthens mental calculation with larger numbers and prepares for multi-step division.',
            concepts:
                'Two to three digit dividends, one to two digit divisors, partial quotients, managing remainders, sequential calculation under time pressure.',
        },
        L3: {
            title: 'Advanced',
            importance: 'Develops accuracy and speed with complex division problems.',
            concepts:
                'Three to four digit dividends, two to three digit divisors, multi-step division, regular practice of remainders, enhancing mental computation stamina.',
        },
        L4: {
            title: 'Pro',
            importance:
                'Prepares learners for high-level mental division challenges.',
            concepts:
                'Four digit dividends, two to three digit divisors, complex multi-step problems, quick remainders handling, mastering Abacus division techniques under tight timing.',
        },
    },
};

// ===================== ADD/SUB  GAMES =====================

const ADD_SUB_L1 = [
    {
        id: 'ADD_SUB_L1_1',
        name: 'Sirius',
        digitCount: 1,
        operations: ['add', 'subtract'],
        numberCount: 3,
        delay: 1000,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 10,
    },
    {
        id: 'ADD_SUB_L1_2',
        name: 'Vega',
        digitCount: 1,
        operations: ['add', 'subtract'],
        numberCount: 4,
        delay: 1000,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 12,
    },
    {
        id: 'ADD_SUB_L1_3',
        name: 'Altair',
        digitCount: 1,
        operations: ['add', 'subtract'],
        numberCount: 5,
        delay: 950,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 12,
    },
    {
        id: 'ADD_SUB_L1_4',
        name: 'Rigel',
        digitCount: 1,
        operations: ['add', 'subtract'],
        numberCount: 6,
        delay: 900,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 12,
    },
    {
        id: 'ADD_SUB_L1_5',
        name: 'Deneb',
        digitCount: 1,
        operations: ['add', 'subtract'],
        numberCount: 8,
        delay: 850,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 15,
    },
    {
        id: 'ADD_SUB_L1_6',
        name: 'Polaris',
        digitCount: 1,
        operations: ['add', 'subtract'],
        numberCount: 10,
        delay: 800,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 15,
    },
    {
        id: 'ADD_SUB_L1_7',
        name: 'Antares',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 3,
        delay: 1000,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 12,
    },
    {
        id: 'ADD_SUB_L1_8',
        name: 'Spica',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 4,
        delay: 950,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 12,
    },
    {
        id: 'ADD_SUB_L1_9',
        name: 'Aldebaran',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 5,
        delay: 900,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 12,
    },
    {
        id: 'ADD_SUB_L1_10',
        name: 'Betelgeuse',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 6,
        delay: 850,
        level: 'ADD_SUB_L1',
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
        numberOfQuestions: 15,
    },
];

const ADD_SUB_L2 = [
    {
        id: 'ADD_SUB_L2_1',
        name: 'Nova',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 4,
        delay: 900,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_2',
        name: 'Lyra',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 5,
        delay: 850,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 16,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_3',
        name: 'Cygnus',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 6,
        delay: 800,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 17,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_4',
        name: 'Orion',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 7,
        delay: 750,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_5',
        name: 'Perseus',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 8,
        delay: 700,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_6',
        name: 'Phoenix',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 10,
        delay: 650,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_7',
        name: 'Draco',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 3,
        delay: 900,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_8',
        name: 'Aquila',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 4,
        delay: 850,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 16,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_9',
        name: 'Hydra',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 5,
        delay: 800,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 17,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L2_10',
        name: 'Centauri',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 6,
        delay: 750,
        level: 'ADD_SUB_L2',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const ADD_SUB_L3 = [
    {
        id: 'ADD_SUB_L3_1',
        name: 'Procyon',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 8,
        delay: 700,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_2',
        name: 'Regulus',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 10,
        delay: 650,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_3',
        name: 'Capella',
        digitCount: 2,
        operations: ['add', 'subtract'],
        numberCount: 12,
        delay: 600,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_4',
        name: 'Bellatrix',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 5,
        delay: 700,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_5',
        name: 'Mintaka',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 7,
        delay: 650,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_6',
        name: 'Alnilam',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 9,
        delay: 600,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_7',
        name: 'Alnitak',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 11,
        delay: 550,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_8',
        name: 'Fomalhaut',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 13,
        delay: 500,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_9',
        name: 'Achernar',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 15,
        delay: 450,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L3_10',
        name: 'Canopus',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 18,
        delay: 400,
        level: 'ADD_SUB_L3',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const ADD_SUB_L4 = [
    {
        id: 'ADD_SUB_L4_1',
        name: 'Quasar',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 8,
        delay: 600,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_2',
        name: 'Pulsar',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 10,
        delay: 550,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_3',
        name: 'Nova',
        digitCount: 3,
        operations: ['add', 'subtract'],
        numberCount: 12,
        delay: 500,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_4',
        name: 'Magnetar',
        digitCount: 4,
        operations: ['add', 'subtract'],
        numberCount: 6,
        delay: 600,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_5',
        name: 'Hyperion',
        digitCount: 4,
        operations: ['add', 'subtract'],
        numberCount: 8,
        delay: 550,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_6',
        name: 'Titan',
        digitCount: 4,
        operations: ['add', 'subtract'],
        numberCount: 10,
        delay: 500,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_7',
        name: 'Cosmos',
        digitCount: 5,
        operations: ['add', 'subtract'],
        numberCount: 6,
        delay: 550,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_8',
        name: 'Infinity',
        digitCount: 5,
        operations: ['add', 'subtract'],
        numberCount: 8,
        delay: 500,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_9',
        name: 'Eternity',
        digitCount: 5,
        operations: ['add', 'subtract'],
        numberCount: 10,
        delay: 450,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 30,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'ADD_SUB_L4_10',
        name: 'Singularity',
        digitCount: 6,
        operations: ['add', 'subtract'],
        numberCount: 10,
        delay: 400,
        level: 'ADD_SUB_L4',
        numberOfQuestions: 30,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

// ===================== MULTIPLICATION  GAMES =====================

const MUL_L1 = [
    {
        id: 'MUL_L1_1',
        name: 'Timespark',
        digitCount: 1,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1500,
        level: 'MUL_L1',
        numberOfQuestions: 10,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_2',
        name: 'DoubleStar',
        digitCount: 1,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1400,
        level: 'MUL_L1',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_3',
        name: 'Triplex',
        digitCount: 1,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1300,
        level: 'MUL_L1',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_4',
        name: 'TwinCore',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1500,
        level: 'MUL_L1',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_5',
        name: 'Quadra',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1400,
        level: 'MUL_L1',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_6',
        name: 'Helix',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1300,
        level: 'MUL_L1',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_7',
        name: 'Titan',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1600,
        level: 'MUL_L1',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_8',
        name: 'Colossus',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1500,
        level: 'MUL_L1',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_9',
        name: 'Infinity',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1400,
        level: 'MUL_L1',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L1_10',
        name: 'Singularity',
        digitCount: 4,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1700,
        level: 'MUL_L1',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const MUL_L2 = [
    {
        id: 'MUL_L2_1',
        name: 'Spark',
        digitCount: 1,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1200,
        level: 'MUL_L2',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_2',
        name: 'Flare',
        digitCount: 1,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1200,
        level: 'MUL_L2',
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_3',
        name: 'Nova',
        digitCount: 1,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1100,
        level: 'MUL_L2',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_4',
        name: 'Pulse',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1100,
        level: 'MUL_L2',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_5',
        name: 'Fusion',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1100,
        level: 'MUL_L2',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_6',
        name: 'Radiant',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1000,
        level: 'MUL_L2',
        numberOfQuestions: 16,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_7',
        name: 'Ignite',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 5,
        delay: 1000,
        level: 'MUL_L2',
        numberOfQuestions: 16,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_8',
        name: 'Orbit',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1000,
        level: 'MUL_L2',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_9',
        name: 'Helios',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 4,
        delay: 900,
        level: 'MUL_L2',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L2_10',
        name: 'Zenith',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 5,
        delay: 900,
        level: 'MUL_L2',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const MUL_L3 = [
    {
        id: 'MUL_L3_1',
        name: 'Forge',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1200,
        level: 'MUL_L3',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_2',
        name: 'Anvil',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1200,
        level: 'MUL_L3',
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_3',
        name: 'Hammer',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1000,
        level: 'MUL_L3',
        numberOfQuestions: 16,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_4',
        name: 'Pulse',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1000,
        level: 'MUL_L3',
        numberOfQuestions: 16,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_5',
        name: 'Drive',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 4,
        delay: 900,
        level: 'MUL_L3',
        numberOfQuestions: 16,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_6',
        name: 'Surge',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 5,
        delay: 900,
        level: 'MUL_L3',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_7',
        name: 'Momentum',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 5,
        delay: 800,
        level: 'MUL_L3',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_8',
        name: 'Vector',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 6,
        delay: 800,
        level: 'MUL_L3',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_9',
        name: 'Catalyst',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 4,
        delay: 750,
        level: 'MUL_L3',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L3_10',
        name: 'Vortex',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 5,
        delay: 750,
        level: 'MUL_L3',
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const MUL_L4 = [
    {
        id: 'MUL_L4_1',
        name: 'Quasar',
        digitCount: 2,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1200,
        level: 'MUL_L4',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_2',
        name: 'Pulsar',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1200,
        level: 'MUL_L4',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_3',
        name: 'Nebula',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 3,
        delay: 1100,
        level: 'MUL_L4',
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_4',
        name: 'Aurora',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1100,
        level: 'MUL_L4',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_5',
        name: 'Galaxy',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 4,
        delay: 1000,
        level: 'MUL_L4',
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_6',
        name: 'Cosmos',
        digitCount: 3,
        operations: ['multiply'],
        numberCount: 6,
        delay: 1100,
        level: 'MUL_L4',
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_7',
        name: 'Orbit',
        digitCount: 4,
        operations: ['multiply'],
        numberCount: 2,
        delay: 1000,
        level: 'MUL_L4',
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_8',
        name: 'Zenith',
        digitCount: 4,
        operations: ['multiply'],
        numberCount: 2,
        delay: 950,
        level: 'MUL_L4',
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_9',
        name: 'NovaCore',
        digitCount: 4,
        operations: ['multiply'],
        numberCount: 2,
        delay: 900,
        level: 'MUL_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'MUL_L4_10',
        name: 'Supernova',
        digitCount: 4,
        operations: ['multiply'],
        numberCount: 2,
        delay: 900,
        level: 'MUL_L4',
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

// ===================== DIVISION  GAMES =====================

const DIV_L1 = [
    {
        id: 'DIV_L1_1',
        name: 'SplitOne',
        digitCount: 1,
        divisorDigits: 1,
        operations: ['divide'],
        numberCount: 2,
        delay: 1500,
        level: 'DIV_L1',
        remainderAllowed: false,
        numberOfQuestions: 10,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L1_2',
        name: 'SplitTwo',
        digitCount: 1,
        divisorDigits: 1,
        operations: ['divide'],
        numberCount: 3,
        delay: 1400,
        level: 'DIV_L1',
        remainderAllowed: false,
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L1_3',
        name: 'SplitThree',
        digitCount: 2,
        divisorDigits: 1,
        operations: ['divide'],
        numberCount: 2,
        delay: 1400,
        level: 'DIV_L1',
        remainderAllowed: false,
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const DIV_L2 = [
    {
        id: 'DIV_L2_1',
        name: 'DivideStar',
        digitCount: 2,
        divisorDigits: 1,
        operations: ['divide'],
        numberCount: 2,
        delay: 1400,
        level: 'DIV_L2',
        remainderAllowed: true,
        numberOfQuestions: 12,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L2_2',
        name: 'DivideNova',
        digitCount: 2,
        divisorDigits: 1,
        operations: ['divide'],
        numberCount: 3,
        delay: 1300,
        level: 'DIV_L2',
        remainderAllowed: true,
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L2_3',
        name: 'DivideCore',
        digitCount: 2,
        divisorDigits: 2,
        operations: ['divide'],
        numberCount: 2,
        delay: 1300,
        level: 'DIV_L2',
        remainderAllowed: true,
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L2_4',
        name: 'DividePulse',
        digitCount: 3,
        divisorDigits: 1,
        operations: ['divide'],
        numberCount: 2,
        delay: 1300,
        level: 'DIV_L2',
        remainderAllowed: true,
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const DIV_L3 = [
    {
        id: 'DIV_L3_1',
        name: 'QuotientX',
        digitCount: 3,
        divisorDigits: 2,
        operations: ['divide'],
        numberCount: 2,
        delay: 1200,
        level: 'DIV_L3',
        remainderAllowed: true,
        numberOfQuestions: 15,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L3_2',
        name: 'QuotientStar',
        digitCount: 3,
        divisorDigits: 2,
        operations: ['divide'],
        numberCount: 3,
        delay: 1100,
        level: 'DIV_L3',
        remainderAllowed: true,
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L3_3',
        name: 'QuotientNova',
        digitCount: 3,
        divisorDigits: 3,
        operations: ['divide'],
        numberCount: 2,
        delay: 1100,
        level: 'DIV_L3',
        remainderAllowed: true,
        numberOfQuestions: 18,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L3_4',
        name: 'QuotientCore',
        digitCount: 4,
        divisorDigits: 2,
        operations: ['divide'],
        numberCount: 2,
        delay: 1000,
        level: 'DIV_L3',
        remainderAllowed: true,
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

const DIV_L4 = [
    {
        id: 'DIV_L4_1',
        name: 'MegaDivide',
        digitCount: 4,
        divisorDigits: 2,
        operations: ['divide'],
        numberCount: 2,
        delay: 1000,
        level: 'DIV_L4',
        remainderAllowed: true,
        numberOfQuestions: 20,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L4_2',
        name: 'UltraDivide',
        digitCount: 4,
        divisorDigits: 3,
        operations: ['divide'],
        numberCount: 2,
        delay: 900,
        level: 'DIV_L4',
        remainderAllowed: true,
        numberOfQuestions: 22,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
    {
        id: 'DIV_L4_3',
        name: 'HyperDivide',
        digitCount: 4,
        divisorDigits: 3,
        operations: ['divide'],
        numberCount: 3,
        delay: 900,
        level: 'DIV_L4',
        remainderAllowed: true,
        numberOfQuestions: 25,
        icon: 'https://mxfmj8wrrjv5and6.public.blob.vercel-storage.com/31dbed13-9148-4635-9b09-f6b27a02c84f.png',
    },
];

export {
    GAME_METAS,
    GAME_LEVELS,
    ADD_SUB_L1,
    ADD_SUB_L2,
    ADD_SUB_L3,
    ADD_SUB_L4,
    MUL_L1,
    MUL_L2,
    MUL_L3,
    MUL_L4,
    DIV_L1,
    DIV_L2,
    DIV_L3,
    DIV_L4,
}