// ===================== GAE METAS =====================
const GAME_METAS = [
  {
    name: "Addition & Subtraction",
    code: "ADDSUB",
    levels: ["L1", "L2", "L3", "L4"],
    weightage: 10,
  },
  {
    name: "Multiplication",
    code: "MUL",
    levels: ["L1", "L2", "L3", "L4"],
    weightage: 20,
  },
  {
    name: "Division",
    code: "DIV",
    levels: ["L1", "L2", "L3", "L4"],
    weightage: 30,
  },
];

// ===================== GAME LEVEL DESCRIPTIONS =====================
const GAME_LEVELS = {
  ADDSUB: {
    L1: {
      title: "Beginner",
      importance: "Builds basic mental addition and subtraction skills.",
      concepts:
        "Single digit calculations, short sequences, simple carry/borrow, increasing number of operands.",
    },
    L2: {
      title: "Intermediate",
      importance:
        "Strengthens mental agility and accuracy with larger numbers.",
      concepts:
        "Two digit addition/subtraction, introduction to three digit numbers, longer sequences, maintaining focus under time pressure.",
    },
    L3: {
      title: "Advanced",
      importance:
        "Prepares learners for complex calculations in speed challenges.",
      concepts:
        "Multiple two and three digit numbers, multi-step addition/subtraction, faster calculation under shorter delays.",
    },
    L4: {
      title: "Pro",
      importance:
        "Develops high-speed mental computation and advanced problem-solving.",
      concepts:
        "Three to six digit operations, multi-step sequences, handling carry/borrow over multiple digits, precision under tight timing.",
    },
  },
  MUL: {
    L1: {
      title: "Beginner",
      importance: "Establishes fundamental multiplication skills.",
      concepts:
        "Single and two digit multiplication, small number sequences, visualizing multiplication patterns.",
    },
    L2: {
      title: "Intermediate",
      importance:
        "Builds speed and confidence with multi-digit multiplication.",
      concepts:
        "Two to three digit multipliers, sequences of two to five numbers, mental multiplication strategies, improving calculation speed.",
    },
    L3: {
      title: "Advanced",
      importance: "Enhances mental stamina and advanced multiplication skills.",
      concepts:
        "Multi-digit multiplication, sequences of four to six numbers, combination of speed and accuracy, handling complex multiplications in mind.",
    },
    L4: {
      title: "Pro",
      importance: "Prepares learners for highly challenging mental math.",
      concepts:
        "Higher digit multipliers (up to 4 digits), small but precise sequences, rapid computation under strict time constraints, reinforcing mastery of multiplication patterns.",
    },
  },
  DIV: {
    L1: {
      title: "Beginner",
      importance:
        "Introduces basic division and builds confidence in handling numbers mentally.",
      concepts:
        "Single digit dividends and divisors, understanding division as equal grouping, simple quotients, basic remainders.",
    },
    L2: {
      title: "Intermediate",
      importance:
        "Strengthens mental calculation with larger numbers and prepares for multi-step division.",
      concepts:
        "Two to three digit dividends, one to two digit divisors, partial quotients, managing remainders, sequential calculation under time pressure.",
    },
    L3: {
      title: "Advanced",
      importance: "Develops accuracy and speed with complex division problems.",
      concepts:
        "Three to four digit dividends, two to three digit divisors, multi-step division, regular practice of remainders, enhancing mental computation stamina.",
    },
    L4: {
      title: "Pro",
      importance:
        "Prepares learners for high-level mental division challenges.",
      concepts:
        "Four digit dividends, two to three digit divisors, complex multi-step problems, quick remainders handling, mastering Abacus division techniques under tight timing.",
    },
  },
};

// ===================== ADD/SUB  GAMES =====================

const ADDSUB_L1 = [
  {
    id: "ADDSUB_L1_1",
    name: "Sirius",
    digitCount: 1,
    operations: ["add", "subtract"],
    numberCount: 3,
    delay: 1000,
    level: "ADDSUB_L1",
    icon: "1",
    numberOfQuestions: 10,
  },
  {
    id: "ADDSUB_L1_2",
    name: "Vega",
    digitCount: 1,
    operations: ["add", "subtract"],
    numberCount: 4,
    delay: 1000,
    level: "ADDSUB_L1",
    icon: "2",
    numberOfQuestions: 12,
  },
  {
    id: "ADDSUB_L1_3",
    name: "Altair",
    digitCount: 1,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 950,
    level: "ADDSUB_L1",
    icon: "3",
    numberOfQuestions: 12,
  },
  {
    id: "ADDSUB_L1_4",
    name: "Rigel",
    digitCount: 1,
    operations: ["add", "subtract"],
    numberCount: 6,
    delay: 900,
    level: "ADDSUB_L1",
    icon: "4",
    numberOfQuestions: 12,
  },
  {
    id: "ADDSUB_L1_5",
    name: "Deneb",
    digitCount: 1,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 850,
    level: "ADDSUB_L1",
    icon: "5",
    numberOfQuestions: 15,
  },
  {
    id: "ADDSUB_L1_6",
    name: "Polaris",
    digitCount: 1,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 800,
    level: "ADDSUB_L1",
    icon: "6",
    numberOfQuestions: 15,
  },
  {
    id: "ADDSUB_L1_7",
    name: "Antares",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 3,
    delay: 1000,
    level: "ADDSUB_L1",
    icon: "7",
    numberOfQuestions: 12,
  },
  {
    id: "ADDSUB_L1_8",
    name: "Spica",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 4,
    delay: 950,
    level: "ADDSUB_L1",
    icon: "8",
    numberOfQuestions: 12,
  },
  {
    id: "ADDSUB_L1_9",
    name: "Aldebaran",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 900,
    level: "ADDSUB_L1",
    icon: "9",
    numberOfQuestions: 12,
  },
  {
    id: "ADDSUB_L1_10",
    name: "Betelgeuse",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 6,
    delay: 850,
    level: "ADDSUB_L1",
    icon: "10",
    numberOfQuestions: 15,
  },
];

const ADDSUB_L2 = [
  {
    id: "ADDSUB_L2_1",
    name: "Nova",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 4,
    delay: 900,
    level: "ADDSUB_L2",
    numberOfQuestions: 15,
    icon: "11",
  },
  {
    id: "ADDSUB_L2_2",
    name: "Lyra",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 850,
    level: "ADDSUB_L2",
    numberOfQuestions: 16,
    icon: "12",
  },
  {
    id: "ADDSUB_L2_3",
    name: "Cygnus",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 6,
    delay: 800,
    level: "ADDSUB_L2",
    numberOfQuestions: 17,
    icon: "13",
  },
  {
    id: "ADDSUB_L2_4",
    name: "Orion",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 7,
    delay: 750,
    level: "ADDSUB_L2",
    numberOfQuestions: 18,
    icon: "14",
  },
  {
    id: "ADDSUB_L2_5",
    name: "Perseus",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 700,
    level: "ADDSUB_L2",
    numberOfQuestions: 18,
    icon: "15",
  },
  {
    id: "ADDSUB_L2_6",
    name: "Phoenix",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 650,
    level: "ADDSUB_L2",
    numberOfQuestions: 20,
    icon: "16",
  },
  {
    id: "ADDSUB_L2_7",
    name: "Draco",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 3,
    delay: 900,
    level: "ADDSUB_L2",
    numberOfQuestions: 15,
    icon: "17",
  },
  {
    id: "ADDSUB_L2_8",
    name: "Aquila",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 4,
    delay: 850,
    level: "ADDSUB_L2",
    numberOfQuestions: 16,
    icon: "18",
  },
  {
    id: "ADDSUB_L2_9",
    name: "Hydra",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 800,
    level: "ADDSUB_L2",
    numberOfQuestions: 17,
    icon: "19",
  },
  {
    id: "ADDSUB_L2_10",
    name: "Centauri",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 6,
    delay: 750,
    level: "ADDSUB_L2",
    numberOfQuestions: 18,
    icon: "20",
  },
];

const ADDSUB_L3 = [
  {
    id: "ADDSUB_L3_1",
    name: "Procyon",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 700,
    level: "ADDSUB_L3",
    numberOfQuestions: 20,
    icon: "21",
  },
  {
    id: "ADDSUB_L3_2",
    name: "Regulus",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 650,
    level: "ADDSUB_L3",
    numberOfQuestions: 20,
    icon: "22",
  },
  {
    id: "ADDSUB_L3_3",
    name: "Capella",
    digitCount: 2,
    operations: ["add", "subtract"],
    numberCount: 12,
    delay: 600,
    level: "ADDSUB_L3",
    numberOfQuestions: 22,
    icon: "23",
  },
  {
    id: "ADDSUB_L3_4",
    name: "Bellatrix",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 700,
    level: "ADDSUB_L3",
    numberOfQuestions: 20,
    icon: "24",
  },
  {
    id: "ADDSUB_L3_5",
    name: "Mintaka",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 7,
    delay: 650,
    level: "ADDSUB_L3",
    numberOfQuestions: 22,
    icon: "25",
  },
  {
    id: "ADDSUB_L3_6",
    name: "Alnilam",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 9,
    delay: 600,
    level: "ADDSUB_L3",
    numberOfQuestions: 22,
    icon: "26",
  },
  {
    id: "ADDSUB_L3_7",
    name: "Alnitak",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 11,
    delay: 550,
    level: "ADDSUB_L3",
    numberOfQuestions: 25,
    icon: "27",
  },
  {
    id: "ADDSUB_L3_8",
    name: "Fomalhaut",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 13,
    delay: 500,
    level: "ADDSUB_L3",
    numberOfQuestions: 25,
    icon: "28",
  },
  {
    id: "ADDSUB_L3_9",
    name: "Achernar",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 15,
    delay: 450,
    level: "ADDSUB_L3",
    numberOfQuestions: 25,
    icon: "29",
  },
  {
    id: "ADDSUB_L3_10",
    name: "Canopus",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 18,
    delay: 400,
    level: "ADDSUB_L3",
    numberOfQuestions: 25,
    icon: "30",
  },
];

const ADDSUB_L4 = [
  {
    id: "ADDSUB_L4_1",
    name: "Quasar",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 600,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "31",
  },
  {
    id: "ADDSUB_L4_2",
    name: "Pulsar",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 550,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "32",
  },
  {
    id: "ADDSUB_L4_3",
    name: "Nova",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 12,
    delay: 500,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "33",
  },
  {
    id: "ADDSUB_L4_4",
    name: "Magnetar",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 6,
    delay: 600,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "34",
  },
  {
    id: "ADDSUB_L4_5",
    name: "Hyperion",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 550,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "35",
  },
  {
    id: "ADDSUB_L4_6",
    name: "Titan",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 500,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "36",
  },
  {
    id: "ADDSUB_L4_7",
    name: "Cosmos",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 6,
    delay: 550,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "37",
  },
  {
    id: "ADDSUB_L4_8",
    name: "Infinity",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 500,
    level: "ADDSUB_L4",
    numberOfQuestions: 25,
    icon: "38",
  },
  {
    id: "ADDSUB_L4_9",
    name: "Eternity",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 450,
    level: "ADDSUB_L4",
    numberOfQuestions: 30,
    icon: "1",
  },
  {
    id: "ADDSUB_L4_10",
    name: "Singularity",
    digitCount: 6,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 400,
    level: "ADDSUB_L4",
    numberOfQuestions: 30,
    icon: "2",
  },
];

// ===================== MULTIPLICATION  GAMES =====================

const MUL_L1 = [
  {
    id: "MUL_L1_1",
    name: "Timespark",
    digitCount: 1,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1500,
    level: "MUL_L1",
    numberOfQuestions: 10,
    icon: "3",
  },
  {
    id: "MUL_L1_2",
    name: "DoubleStar",
    digitCount: 1,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1400,
    level: "MUL_L1",
    numberOfQuestions: 12,
    icon: "4",
  },
  {
    id: "MUL_L1_3",
    name: "Triplex",
    digitCount: 1,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1300,
    level: "MUL_L1",
    numberOfQuestions: 12,
    icon: "5",
  },
  {
    id: "MUL_L1_4",
    name: "TwinCore",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1500,
    level: "MUL_L1",
    numberOfQuestions: 12,
    icon: "6",
  },
  {
    id: "MUL_L1_5",
    name: "Quadra",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1400,
    level: "MUL_L1",
    numberOfQuestions: 12,
    icon: "7",
  },
  {
    id: "MUL_L1_6",
    name: "Helix",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1300,
    level: "MUL_L1",
    numberOfQuestions: 12,
    icon: "8",
  },
  {
    id: "MUL_L1_7",
    name: "Titan",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1600,
    level: "MUL_L1",
    numberOfQuestions: 12,
    icon: "9",
  },
  {
    id: "MUL_L1_8",
    name: "Colossus",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1500,
    level: "MUL_L1",
    numberOfQuestions: 12,
    icon: "10",
  },
  {
    id: "MUL_L1_9",
    name: "Infinity",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1400,
    level: "MUL_L1",
    numberOfQuestions: 15,
    icon: "11",
  },
  {
    id: "MUL_L1_10",
    name: "Singularity",
    digitCount: 4,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1700,
    level: "MUL_L1",
    numberOfQuestions: 15,
    icon: "12",
  },
];

const MUL_L2 = [
  {
    id: "MUL_L2_1",
    name: "Spark",
    digitCount: 1,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1200,
    level: "MUL_L2",
    numberOfQuestions: 12,
    icon: "13",
  },
  {
    id: "MUL_L2_2",
    name: "Flare",
    digitCount: 1,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1200,
    level: "MUL_L2",
    numberOfQuestions: 12,
    icon: "14",
  },
  {
    id: "MUL_L2_3",
    name: "Nova",
    digitCount: 1,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1100,
    level: "MUL_L2",
    numberOfQuestions: 15,
    icon: "15",
  },
  {
    id: "MUL_L2_4",
    name: "Pulse",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1100,
    level: "MUL_L2",
    numberOfQuestions: 15,
    icon: "16",
  },
  {
    id: "MUL_L2_5",
    name: "Fusion",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1100,
    level: "MUL_L2",
    numberOfQuestions: 15,
    icon: "17",
  },
  {
    id: "MUL_L2_6",
    name: "Radiant",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1000,
    level: "MUL_L2",
    numberOfQuestions: 16,
    icon: "18",
  },
  {
    id: "MUL_L2_7",
    name: "Ignite",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 5,
    delay: 1000,
    level: "MUL_L2",
    numberOfQuestions: 16,
    icon: "19",
  },
  {
    id: "MUL_L2_8",
    name: "Orbit",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1000,
    level: "MUL_L2",
    numberOfQuestions: 18,
    icon: "20",
  },
  {
    id: "MUL_L2_9",
    name: "Helios",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 4,
    delay: 900,
    level: "MUL_L2",
    numberOfQuestions: 18,
    icon: "21",
  },
  {
    id: "MUL_L2_10",
    name: "Zenith",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 5,
    delay: 900,
    level: "MUL_L2",
    numberOfQuestions: 20,
    icon: "22",
  },
];

const MUL_L3 = [
  {
    id: "MUL_L3_1",
    name: "Forge",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1200,
    level: "MUL_L3",
    numberOfQuestions: 15,
    icon: "23",
  },
  {
    id: "MUL_L3_2",
    name: "Anvil",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1200,
    level: "MUL_L3",
    numberOfQuestions: 15,
    icon: "24",
  },
  {
    id: "MUL_L3_3",
    name: "Hammer",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1000,
    level: "MUL_L3",
    numberOfQuestions: 16,
    icon: "25",
  },
  {
    id: "MUL_L3_4",
    name: "Pulse",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1000,
    level: "MUL_L3",
    numberOfQuestions: 16,
    icon: "26",
  },
  {
    id: "MUL_L3_5",
    name: "Drive",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 4,
    delay: 900,
    level: "MUL_L3",
    numberOfQuestions: 16,
    icon: "27",
  },
  {
    id: "MUL_L3_6",
    name: "Surge",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 5,
    delay: 900,
    level: "MUL_L3",
    numberOfQuestions: 18,
    icon: "28",
  },
  {
    id: "MUL_L3_7",
    name: "Momentum",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 5,
    delay: 800,
    level: "MUL_L3",
    numberOfQuestions: 18,
    icon: "29",
  },
  {
    id: "MUL_L3_8",
    name: "Vector",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 6,
    delay: 800,
    level: "MUL_L3",
    numberOfQuestions: 20,
    icon: "30",
  },
  {
    id: "MUL_L3_9",
    name: "Catalyst",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 4,
    delay: 750,
    level: "MUL_L3",
    numberOfQuestions: 20,
    icon: "31",
  },
  {
    id: "MUL_L3_10",
    name: "Vortex",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 5,
    delay: 750,
    level: "MUL_L3",
    numberOfQuestions: 22,
    icon: "32",
  },
];

const MUL_L4 = [
  {
    id: "MUL_L4_1",
    name: "Quasar",
    digitCount: 2,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1200,
    level: "MUL_L4",
    numberOfQuestions: 18,
    icon: "33",
  },
  {
    id: "MUL_L4_2",
    name: "Pulsar",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1200,
    level: "MUL_L4",
    numberOfQuestions: 18,
    icon: "34",
  },
  {
    id: "MUL_L4_3",
    name: "Nebula",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 3,
    delay: 1100,
    level: "MUL_L4",
    numberOfQuestions: 18,
    icon: "35",
  },
  {
    id: "MUL_L4_4",
    name: "Aurora",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1100,
    level: "MUL_L4",
    numberOfQuestions: 20,
    icon: "36",
  },
  {
    id: "MUL_L4_5",
    name: "Galaxy",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 4,
    delay: 1000,
    level: "MUL_L4",
    numberOfQuestions: 20,
    icon: "37",
  },
  {
    id: "MUL_L4_6",
    name: "Cosmos",
    digitCount: 3,
    operations: ["multiply"],
    numberCount: 6,
    delay: 1100,
    level: "MUL_L4",
    numberOfQuestions: 22,
    icon: "38",
  },
  {
    id: "MUL_L4_7",
    name: "Orbit",
    digitCount: 4,
    operations: ["multiply"],
    numberCount: 2,
    delay: 1000,
    level: "MUL_L4",
    numberOfQuestions: 22,
    icon: "1",
  },
  {
    id: "MUL_L4_8",
    name: "Zenith",
    digitCount: 4,
    operations: ["multiply"],
    numberCount: 2,
    delay: 950,
    level: "MUL_L4",
    numberOfQuestions: 22,
    icon: "2",
  },
  {
    id: "MUL_L4_9",
    name: "NovaCore",
    digitCount: 4,
    operations: ["multiply"],
    numberCount: 2,
    delay: 900,
    level: "MUL_L4",
    numberOfQuestions: 25,
    icon: "3",
  },
  {
    id: "MUL_L4_10",
    name: "Supernova",
    digitCount: 4,
    operations: ["multiply"],
    numberCount: 2,
    delay: 900,
    level: "MUL_L4",
    numberOfQuestions: 25,
    icon: "4",
  },
];

// ===================== DIVISION  GAMES =====================

const DIV_L1 = [
  {
    id: "DIV_L1_1",
    name: "SplitOne",
    digitCount: 1,
    divisorDigits: 1,
    operations: ["divide"],
    numberCount: 2,
    delay: 1500,
    level: "DIV_L1",
    remainderAllowed: false,
    numberOfQuestions: 10,
    icon: "5",
  },
  {
    id: "DIV_L1_2",
    name: "SplitTwo",
    digitCount: 1,
    divisorDigits: 1,
    operations: ["divide"],
    numberCount: 3,
    delay: 1400,
    level: "DIV_L1",
    remainderAllowed: false,
    numberOfQuestions: 12,
    icon: "6",
  },
  {
    id: "DIV_L1_3",
    name: "SplitThree",
    digitCount: 2,
    divisorDigits: 1,
    operations: ["divide"],
    numberCount: 2,
    delay: 1400,
    level: "DIV_L1",
    remainderAllowed: false,
    numberOfQuestions: 12,
    icon: "7",
  },
];

const DIV_L2 = [
  {
    id: "DIV_L2_1",
    name: "DivideStar",
    digitCount: 2,
    divisorDigits: 1,
    operations: ["divide"],
    numberCount: 2,
    delay: 1400,
    level: "DIV_L2",
    remainderAllowed: true,
    numberOfQuestions: 12,
    icon: "8",
  },
  {
    id: "DIV_L2_2",
    name: "DivideNova",
    digitCount: 2,
    divisorDigits: 1,
    operations: ["divide"],
    numberCount: 3,
    delay: 1300,
    level: "DIV_L2",
    remainderAllowed: true,
    numberOfQuestions: 15,
    icon: "9",
  },
  {
    id: "DIV_L2_3",
    name: "DivideCore",
    digitCount: 2,
    divisorDigits: 2,
    operations: ["divide"],
    numberCount: 2,
    delay: 1300,
    level: "DIV_L2",
    remainderAllowed: true,
    numberOfQuestions: 15,
    icon: "10",
  },
  {
    id: "DIV_L2_4",
    name: "DividePulse",
    digitCount: 3,
    divisorDigits: 1,
    operations: ["divide"],
    numberCount: 2,
    delay: 1300,
    level: "DIV_L2",
    remainderAllowed: true,
    numberOfQuestions: 15,
    icon: "11",
  },
];

const DIV_L3 = [
  {
    id: "DIV_L3_1",
    name: "QuotientX",
    digitCount: 3,
    divisorDigits: 2,
    operations: ["divide"],
    numberCount: 2,
    delay: 1200,
    level: "DIV_L3",
    remainderAllowed: true,
    numberOfQuestions: 15,
    icon: "12",
  },
  {
    id: "DIV_L3_2",
    name: "QuotientStar",
    digitCount: 3,
    divisorDigits: 2,
    operations: ["divide"],
    numberCount: 3,
    delay: 1100,
    level: "DIV_L3",
    remainderAllowed: true,
    numberOfQuestions: 18,
    icon: "13",
  },
  {
    id: "DIV_L3_3",
    name: "QuotientNova",
    digitCount: 3,
    divisorDigits: 3,
    operations: ["divide"],
    numberCount: 2,
    delay: 1100,
    level: "DIV_L3",
    remainderAllowed: true,
    numberOfQuestions: 18,
    icon: "14",
  },
  {
    id: "DIV_L3_4",
    name: "QuotientCore",
    digitCount: 4,
    divisorDigits: 2,
    operations: ["divide"],
    numberCount: 2,
    delay: 1000,
    level: "DIV_L3",
    remainderAllowed: true,
    numberOfQuestions: 20,
    icon: "15",
  },
];

const DIV_L4 = [
  {
    id: "DIV_L4_1",
    name: "MegaDivide",
    digitCount: 4,
    divisorDigits: 2,
    operations: ["divide"],
    numberCount: 2,
    delay: 1000,
    level: "DIV_L4",
    remainderAllowed: true,
    numberOfQuestions: 20,
    icon: "16",
  },
  {
    id: "DIV_L4_2",
    name: "UltraDivide",
    digitCount: 4,
    divisorDigits: 3,
    operations: ["divide"],
    numberCount: 2,
    delay: 900,
    level: "DIV_L4",
    remainderAllowed: true,
    numberOfQuestions: 22,
    icon: "17",
  },
  {
    id: "DIV_L4_3",
    name: "HyperDivide",
    digitCount: 4,
    divisorDigits: 3,
    operations: ["divide"],
    numberCount: 3,
    delay: 900,
    level: "DIV_L4",
    remainderAllowed: true,
    numberOfQuestions: 25,
    icon: "18",
  },
];

const ACHIEVEMENTS_CRITERIA = [
  {
    "id": "LOGIN_STREAK_3",
    "name": "Spark Chain",
    "description": "Play 3 days in a row",
    "category": "daily_streak",
    "target": 3
  },
  {
    "id": "LOGIN_STREAK_7",
    "name": "Weekly Rhythm",
    "description": "Play 7 days in a row",
    "category": "daily_streak",
    "target": 7
  },
  {
    "id": "LOGIN_STREAK_22",
    "name": "Discipline Mind",
    "description": "Play 22 days in a row",
    "category": "daily_streak",
    "target": 22
  },
  {
    "id": "GAMES_TOTAL_25",
    "name": "First 25",
    "description": "Complete 25 games total",
    "category": "games_total",
    "target": 25
  },
  {
    "id": "GAMES_TOTAL_50",
    "name": "Momentum Builder",
    "description": "Complete 50 games total",
    "category": "games_total",
    "target": 50
  },
  {
    "id": "GAMES_TOTAL_100",
    "name": "Century Solver",
    "description": "Complete 100 games total",
    "category": "games_total",
    "target": 100
  },
  {
    "id": "GAMES_TOTAL_200",
    "name": "Dedicated Calculator",
    "description": "Complete 200 games total",
    "category": "games_total",
    "target": 200
  },
  {
    "id": "GAMES_TOTAL_500",
    "name": "Math Marathoner",
    "description": "Complete 500 games total",
    "category": "games_total",
    "target": 500
  },
  {
    "id": "GAMES_TOTAL_1000",
    "name": "Legend of Numbers",
    "description": "Complete 1000 games total",
    "category": "games_total",
    "target": 1000
  },
  {
    "id": "SCORE_TOTAL_500",
    "name": "Point Collector",
    "description": "Reach 500 total score",
    "category": "score_total",
    "target": 500
  },
  {
    "id": "SCORE_TOTAL_1000",
    "name": "Score Climber",
    "description": "Reach 1000 total score",
    "category": "score_total",
    "target": 1000
  },
  {
    "id": "SCORE_TOTAL_2000",
    "name": "Elite Scorer",
    "description": "Reach 2000 total score",
    "category": "score_total",
    "target": 2000
  },
  {
    "id": "SCORE_TOTAL_5000",
    "name": "Score Titan",
    "description": "Reach 5000 total score",
    "category": "score_total",
    "target": 5000
  },
  {
    "id": "SCORE_TOTAL_10000",
    "name": "Grand Master Score",
    "description": "Reach 10000 total score",
    "category": "score_total",
    "target": 10000
  },
  {
    "id": "WIN_STREAK_5",
    "name": "Hot Hands",
    "description": "Unlock a 5-win streak",
    "category": "win_streak",
    "target": 5
  },
  {
    "id": "WIN_STREAK_10",
    "name": "Unbreakable Focus",
    "description": "Unlock a 10-win streak",
    "category": "win_streak",
    "target": 10
  },
  {
    "id": "WIN_STREAK_20",
    "name": "Streak Legend",
    "description": "Unlock a 20-win streak",
    "category": "win_streak",
    "target": 20
  },
  {
    "id": "FLASH_ADDSUB_ALL_COMPLETED",
    "name": "Flash AddSub Master",
    "description": "Complete all Flash ADDSUB levels",
    "category": "flash_category_complete",
    "target": "ADDSUB_ALL"
  },
  {
    "id": "FLASH_MUL_ALL_COMPLETED",
    "name": "Flash Multiplication Master",
    "description": "Complete all Flash MUL levels",
    "category": "flash_category_complete",
    "target": "MUL_ALL"
  },
  {
    "id": "FLASH_DIV_ALL_COMPLETED",
    "name": "Flash Division Master",
    "description": "Complete all Flash DIV levels",
    "category": "flash_category_complete",
    "target": "DIV_ALL"
  }
];

export {
  GAME_METAS,
  GAME_LEVELS,
  ADDSUB_L1,
  ADDSUB_L2,
  ADDSUB_L3,
  ADDSUB_L4,
  MUL_L1,
  MUL_L2,
  MUL_L3,
  MUL_L4,
  DIV_L1,
  DIV_L2,
  DIV_L3,
  DIV_L4,
  ACHIEVEMENTS_CRITERIA
};
