export const MOCK_API_DELAY = 0;

export const USERS = [
  {
    email: "subscribed@test.com",
    password: "1",
    subscribedOn: 1765798676514,
    subscriptionExpiration: 1797334676514,
    term: "YEAR",
    status: "SUBSCRIBED",
  },
  {
    email: "unsubscribed@test.com",
    password: "1",
    subscribedOn: null,
    subscriptionExpiration: null,
    term: null,
    status: "UNSUBSCRIBED",
  },
  {
    email: "trial@test.com",
    password: "1",
    subscribedOn: 1765798676514,
    subscriptionExpiration: 1766403476514,
    term: "WEEK",
    status: "TRIAL",
  },
];

export const REPORT = {
  sessions: 40,
  accuracy: 95,
  streak: 7,
  achievements: 12,
};

const millisecondsInADay = 24 * 60 * 60 * 1000;
const today = Date.now();

export const ACTIVITIES = [
  {
    gameName: "1. Pluto",
    gamePlayedAt: new Date(today),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "2. Mercury",
    gamePlayedAt: new Date(today),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: false,
  },
  {
    gameName: "3. Venus",
    gamePlayedAt: new Date(today - 1 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "4. Earth",
    gamePlayedAt: new Date(today - 1 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "5.Mars",
    gamePlayedAt: new Date(today - 2 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: false,
  },
  {
    gameName: "6. Jupiter",
    gamePlayedAt: new Date(today - 2 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "7. Saturn",
    gamePlayedAt: new Date(today - 2 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "8. Uranus",
    gamePlayedAt: new Date(today - 2 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "9. regular",
    gamePlayedAt: new Date(today - 2 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 15,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "10. Pluto",
    gamePlayedAt: new Date(today - 3 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "11. Mercury",
    gamePlayedAt: new Date(today - 3 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "12. Venus",
    gamePlayedAt: new Date(today - 3 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "13. Earth",
    gamePlayedAt: new Date(today - 3 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 11,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "14. Mars",
    gamePlayedAt: new Date(today - 3 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "15. Jupiter",
    gamePlayedAt: new Date(today - 3 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: false,
  },
  {
    gameName: "16. Saturn",
    gamePlayedAt: new Date(today - 3 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "17. Uranus",
    gamePlayedAt: new Date(today - 4 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "18. Neptune",
    gamePlayedAt: new Date(today - 4 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "19. Mercury",
    gamePlayedAt: new Date(today - 4 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "20. Venus",
    gamePlayedAt: new Date(today - 5 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "21. Earth",
    gamePlayedAt: new Date(today - 5 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "22. Mars",
    gamePlayedAt: new Date(today - 5 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "23. Jupiter",
    gamePlayedAt: new Date(today - 6 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: false,
  },
  {
    gameName: "24. Saturn",
    gamePlayedAt: new Date(today - 6 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "25. Pluto",
    gamePlayedAt: new Date(today - 7 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "26. Uranus",
    gamePlayedAt: new Date(today - 8 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "27. Neptune",
    gamePlayedAt: new Date(today - 9 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "28. Pluto",
    gamePlayedAt: new Date(today - 10 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: false,
  },
  {
    gameName: "29. Mercury",
    gamePlayedAt: new Date(today - 11 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: true,
  },
  {
    gameName: "30. Venus",
    gamePlayedAt: new Date(today - 11 * millisecondsInADay),
    gameType: "regular",
    totalQuestions: 10,
    correctAnswers: 9,
    correctness: true,
  },
  {
    gameName: "31. Earth",
    gamePlayedAt: new Date(today  - 11 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 8,
    correctness: true,
  },
  {
    gameName: "32. Mars",
    gamePlayedAt: new Date(today - 12 * millisecondsInADay),
    gameType: "flash",
    totalQuestions: 10,
    correctAnswers: 10,
    correctness: false,
  },
];

export const PROGRESS_REPORT = {
  totalSessions: 80,
  accuracyRate: 90,
  currentStreak: 7,
  achievements: ["First Steps", "Consistency"],
  performanceTrend: [
    85, 88, 90, 92, 10, 94, 90, 93, 95, 97, 99, 100, 98, 96, 94, 92, 90, 88, 85,
    83, 81, 79, 77, 75, 73, 71, 69, 67, 65, 75,
  ],
  aiSuggestions: ["Practice subtraction more", "Try timed challenges"],
  recentActivities: ACTIVITIES.slice(0, 5),
};
