export const USERS = [
  {
    email: "subscribed@test.com",
    password: "1",
    subscribedOn: 1765798676514,
    subscriptionExpiration: 1797334676514,
    term: "YEAR",
    status: "SUBSCRIBED",
  },
  {
    email: "unsubscribed@test.com",
    password: "1",
    subscribedOn: null,
    subscriptionExpiration: null,
    term: null,
    status: "UNSUBSCRIBED",
  },
  {
    email: "trial@test.com",
    password: "1",
    subscribedOn: 1765798676514,
    subscriptionExpiration: 1766403476514,
    term: "WEEK",
    status: "TRIAL",
  },
];

export const REPORT = {
  sessions: 40,
  accuracy: 95,
  streak: 7,
  achievements: 12,
};

export const PRACTICE_GAMES = [
  {
    id: "1",
    name: "Pluto",
    planet: "Pluto",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 1000,
    color: "from-slate-400 to-slate-600",
    icon: "🪐",
  },
  {
    id: "2",
    name: "Mercury",
    planet: "Mercury",
    digitCount: 2,
    operations: ["add"],
    numberCount: 4,
    delay: 1500,
    color: "from-orange-400 to-orange-600",
    icon: "☿️",
  },
  {
    id: "3",
    name: "Venus",
    planet: "Venus",
    digitCount: 3,
    operations: ["add"],
    numberCount: 6,
    delay: 1200,
    color: "from-yellow-400 to-amber-600",
    icon: "♀️",
  },
  {
    id: "4",
    name: "Mars",
    planet: "Mars",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 7,
    delay: 900,
    color: "from-red-400 to-red-600",
    icon: "♂️",
  },
  {
    id: "5",
    name: "Jupiter",
    planet: "Jupiter",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 800,
    color: "from-orange-500 to-yellow-600",
    icon: "♃",
  },
  {
    id: "6",
    name: "Saturn",
    planet: "Saturn",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 700,
    color: "from-yellow-500 to-amber-700",
    icon: "♄",
  },
  {
    id: "7",
    name: "Uranus",
    planet: "Uranus",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 9,
    delay: 750,
    color: "from-cyan-400 to-blue-600",
    icon: "♅",
  },
  {
    id: "8",
    name: "Neptune",
    planet: "Neptune",
    digitCount: 6,
    operations: ["add", "subtract"],
    numberCount: 12,
    delay: 600,
    color: "from-blue-500 to-indigo-700",
    icon: "♆",
  },
];

export const TOURNAMENT_GAMES = [
  {
    id: "1",
    name: "Pluto",
    planet: "Pluto",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 1000,
    color: "from-slate-400 to-slate-600",
    icon: "🪐",
  },
  {
    id: "2",
    name: "Mercury",
    planet: "Mercury",
    digitCount: 2,
    operations: ["add"],
    numberCount: 4,
    delay: 1500,
    color: "from-orange-400 to-orange-600",
    icon: "☿️",
  },
  {
    id: "3",
    name: "Venus",
    planet: "Venus",
    digitCount: 3,
    operations: ["add"],
    numberCount: 6,
    delay: 1200,
    color: "from-yellow-400 to-amber-600",
    icon: "♀️",
  },
  {
    id: "4",
    name: "Mars",
    planet: "Mars",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 7,
    delay: 900,
    color: "from-red-400 to-red-600",
    icon: "♂️",
  },
  {
    id: "5",
    name: "Jupiter",
    planet: "Jupiter",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 800,
    color: "from-orange-500 to-yellow-600",
    icon: "♃",
  },
  {
    id: "6",
    name: "Saturn",
    planet: "Saturn",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 700,
    color: "from-yellow-500 to-amber-700",
    icon: "♄",
  },
  {
    id: "7",
    name: "Uranus",
    planet: "Uranus",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 9,
    delay: 750,
    color: "from-cyan-400 to-blue-600",
    icon: "♅",
  },
  {
    id: "8",
    name: "Neptune",
    planet: "Neptune",
    digitCount: 6,
    operations: ["add", "subtract"],
    numberCount: 12,
    delay: 600,
    color: "from-blue-500 to-indigo-700",
    icon: "♆",
  },
];

export const FLASH_GAMES = [
  {
    id: "fg_1",
    name: "Pluto",
    planet: "Pluto",
    digitCount: 3,
    operations: ["add", "subtract"],
    numberCount: 5,
    delay: 1000,
    color: "from-slate-400 to-slate-600",
    icon: "🪐",
  },
  {
    id: "fg_2",
    name: "Mercury",
    planet: "Mercury",
    digitCount: 2,
    operations: ["add"],
    numberCount: 4,
    delay: 1500,
    color: "from-orange-400 to-orange-600",
    icon: "☿️",
  },
  {
    id: "fg_3",
    name: "Venus",
    planet: "Venus",
    digitCount: 3,
    operations: ["add"],
    numberCount: 6,
    delay: 1200,
    color: "from-yellow-400 to-amber-600",
    icon: "♀️",
  },
  {
    id: "fg_4",
    name: "Mars",
    planet: "Mars",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 7,
    delay: 900,
    color: "from-red-400 to-red-600",
    icon: "♂️",
  },
  {
    id: "fg_5",
    name: "Jupiter",
    planet: "Jupiter",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 8,
    delay: 800,
    color: "from-orange-500 to-yellow-600",
    icon: "♃",
  },
  {
    id: "fg_6",
    name: "Saturn",
    planet: "Saturn",
    digitCount: 4,
    operations: ["add", "subtract"],
    numberCount: 10,
    delay: 700,
    color: "from-yellow-500 to-amber-700",
    icon: "♄",
  },
  {
    id: "fg_7",
    name: "Uranus",
    planet: "Uranus",
    digitCount: 5,
    operations: ["add", "subtract"],
    numberCount: 9,
    delay: 750,
    color: "from-cyan-400 to-blue-600",
    icon: "♅",
  },
  {
    id: "fg_8",
    name: "Neptune",
    planet: "Neptune",
    digitCount: 6,
    operations: ["add", "subtract"],
    numberCount: 12,
    delay: 600,
    color: "from-blue-500 to-indigo-700",
    icon: "♆",
  },
];

export const MOCK_API_DELAY = 1000;
